version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-booking
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  booking-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-app-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

volumes:
  pgdata:
